name: Call Terraform Tests, Docs & Compliance

on:
  pull_request:
    branches:
      - master
    types:
      - opened
      - synchronize
      - ready_for_review
jobs:
  tf-tests:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    uses: entur/gh-workflows/.github/workflows/pr-tests-terraform.yml@main
    with:
      module_dirs: '["examples"]'
